MVCBook105/Models/Borrow.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace MVCBook105.Models
{
    public class BorrowISBNViewModel
    {
        public List<Borrow>? Borrows { get; set; }
        public SelectList? ISBNs { get; set; }
        public string? BorrowISBN { get; set; }
        public string? SearchString { get; set; }
    }

    public class Borrow
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "流水号")]
        public string? serialNumber { get; set; }       // 流水号

        [Required]
        [MaxLength(8)]
        public string? ISBN { get; set; }       // 国际标准书号

        [Required]
        [MaxLength(8)]
        [Display(Name = "读者号")]
        public string? readerNumber { get; set; }     // 读者号

        [Display(Name = "借出日期")]
        [DataType(DataType.Date)]
        public DateTime loanDate { get; set; }      // 借出日期

        [Display(Name = "归还日期")]
        [DataType(DataType.Date)]
        public DateTime? returnDate { get; set; }        // 归还日期    
    }
}

MVCBook105/Controllers/BorrowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBook105.Data;
using MVCBook105.Models;

namespace MVCBook105.Controllers
{
    public class BorrowsController : Controller
    {
        private readonly MVCBook105Context _context;

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        public BorrowsController(MVCBook105Context context)
        {
            _context = context;
        }

        // GET: Borrows
        public async Task<IActionResult> Index(string borrowISBN,string searchString)
        {
            if (_context.Borrow == null)
            {
                return Problem("Enity set 'MvcBook105Context.Borrow' is null.");
            }

            // Use LINQ to get list of ISBNs.
            IQueryable<string> ISBNQuery = from m in _context.Borrow orderby m.ISBN select m.ISBN;

            var borrows = from b in _context.Borrow select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                borrows = borrows.Where(s => s.serialNumber!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(borrowISBN))
            {
                borrows = borrows.Where(x => x.ISBN == borrowISBN);
            }

            var borrowISBNVM = new BorrowISBNViewModel
            {
                ISBNs = new SelectList(await ISBNQuery.Distinct().ToListAsync()),
                Borrows = await borrows.ToListAsync()
            };

            return View(borrowISBNVM);
        }

        // GET: Borrows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrow = await _context.Borrow
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrow == null)
            {
                return NotFound();
            }

            return View(borrow);
        }

        // GET: Borrows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,serialNumber,ISBN,readerNumber,loanDate,returnDate")] Borrow borrow)
        {
            if (ModelState.IsValid)
            {
                _context.Add(borrow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(borrow);
        }

        // GET: Borrows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrow = await _context.Borrow.FindAsync(id);
            if (borrow == null)
            {
                return NotFound();
            }
            return View(borrow);
        }

        // POST: Borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,serialNumber,ISBN,readerNumber,loanDate,returnDate")] Borrow borrow)
        {
            if (id != borrow.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(borrow);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BorrowExists(borrow.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(borrow);
        }

        // GET: Borrows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var borrow = await _context.Borrow
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrow == null)
            {
                return NotFound();
            }

            return View(borrow);
        }

        // POST: Borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var borrow = await _context.Borrow.FindAsync(id);
            if (borrow != null)
            {
                _context.Borrow.Remove(borrow);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BorrowExists(int id)
        {
            return _context.Borrow.Any(e => e.Id == id);
        }
    }
}

MVCBook105/Views/Borrows/Create.cshtml
@model MVCBook105.Models.Borrow

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Borrow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="serialNumber" class="control-label"></label>
                <input asp-for="serialNumber" class="form-control" />
                <span asp-validation-for="serialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="readerNumber" class="control-label"></label>
                <input asp-for="readerNumber" class="form-control" />
                <span asp-validation-for="readerNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="loanDate" class="control-label"></label>
                <input asp-for="loanDate" class="form-control" />
                <span asp-validation-for="loanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="returnDate" class="control-label"></label>
                <input asp-for="returnDate" class="form-control" />
                <span asp-validation-for="returnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCBook105/Views/Borrows/Delete.cshtml
@model MVCBook105.Models.Borrow

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Borrow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.serialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.serialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.readerNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.readerNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.loanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.loanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.returnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.returnDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCBook105/Views/Borrows/Details.cshtml
@model MVCBook105.Models.Borrow

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Borrow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.serialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.serialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.readerNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.readerNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.loanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.loanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.returnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.returnDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCBook105/Views/Borrows/Edit.cshtml
@model MVCBook105.Models.Borrow

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Borrow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="serialNumber" class="control-label"></label>
                <input asp-for="serialNumber" class="form-control" />
                <span asp-validation-for="serialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="readerNumber" class="control-label"></label>
                <input asp-for="readerNumber" class="form-control" />
                <span asp-validation-for="readerNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="loanDate" class="control-label"></label>
                <input asp-for="loanDate" class="form-control" />
                <span asp-validation-for="loanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="returnDate" class="control-label"></label>
                <input asp-for="returnDate" class="form-control" />
                <span asp-validation-for="returnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCBook105/Views/Borrows/Index.cshtml
@model MVCBook105.Models.BorrowISBNViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Borrow</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Borrows" asp-action="Index" method="get">
    <p>
        <select asp-for="BorrowISBN" asp-items="Model.ISBNs">
            <option value="">All</option>
        </select>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="筛选" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Borrows![0].serialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Borrows![0].ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Borrows![0].readerNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Borrows![0].loanDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Borrows![0].returnDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Borrows!) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.serialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.readerNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.loanDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.returnDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>